name: nodered
version: 0.13
summary: A visual tool for wiring the Internet of Things
description: Node-RED is a tool for wiring together hardware devices, APIs and online services in new and interesting ways.
confinement: strict
grade: stable

apps:
  red:
    daemon: simple
    command: bin/launch
    plugs:
      - network-bind
      - network

parts:
  red:
    plugin: nodejs
    node-packages:
      - node-red
  settings:
    plugin: dump
    source: settings
    filesets:
      settings:
        - .
    organize:
      start.sh : bin/launch
    snap: 
      - .
    filesets:
      all: [ . ]
